import 'opcoes_escolaridade_formacao.dart';

/// Lista predefinida de cargos. Inclui "Outra (especificar)" para cadastro de cargo não listado.
const List<String> opcoesCargo = [
  'Secretário Adjunto',
  'Assistente de Direção III',
  'Assessor(a) Técnico(a) de Direção II',
  'Assessor(a) Especial II',
  'Assistente Administrativo',
  'Analista Administrativo',
  'Auxiliar Administrativo',
  'Motorista',
  'Superintendente',
  'Coordenador(a)',
  'Biólogo(a)',
  'Residência Técnica',
  'Estagiário(a) de Pós Graduação',
  'Contador(a)',
  'Diretor(a) Clínico(a)',
  'Superintendente Administrativo e Financeiro',
  'Superintendente de Enfermagem',
  'Coordenador da Urgência e Emergência',
  'Coordenador de Clínica Médica e Pediátrica',
  'Coordenador de Medicina Intensiva',
  'Coordenador de Enfermagem Cirúrgica e CME',
  'Assessor(a) Jurídico(a)',
  'Coordenador Equipe Multiprofissional',
  'Coordenador Agência Transfusional',
  'Enfermeiro(a)',
  'Técnico de Enfermagem',
  'Técnico de Raio X',
  'Biomédico(a)',
  'Técnico Administrativo',
  'Secretário(a) Administrativo',
  'Analista Agência Transfusional',
  'Administrador',
  'Farmacêutico(a)',
  'Técnico de Gesso',
  'Nutricionista',
  'Técnico de Nutrição',
  'Lactarista',
  'Assistente Social',
  'Fisioterapeuta',
  'Fonoaudiólogo(a)',
  'Psicólogo(a)',
  'Terapeuta Ocupacional',
  'Odontólogo',
  'Analista de Laboratório',
  'Laboratorista',
  'Médico Infectologista',
  'Coordenador de Manutenção e Engenharia Clínica',
  'Auxiliar Operacional',
  'Maqueiro',
  'Coordenador Tecnologia da Informação',
  'Analista de Sistemas',
  'Auxiliar de Almoxarifado',
  'Auxiliar de Rouparia',
  'Vigilante',
  'Engenheiro Clínico',
  'Técnico Engenharia Clínica II',
  'Técnico Engenharia Clínica III',
  'Recepcionista',
  'Telefonista',
  'Médico do Trabalho',
  'Enfermeiro(a) do Trabalho',
  'Engenheiro de Segurança do Trabalho',
  'Técnico Segurança do Trabalho',
  'Diretor Clínico (Não remunerado)',
  'Diretor Técnico',
  'Coordenador de Enfermagem Cirúrgica e CME',
  'Auxiliar de Serviços Gerais',
  'Cozinheiro(a)',
  'Auxiliar de Enfermagem',
  'Bioquímico(a)',
  'Auxiliar de Enfermagem',
  'Técnico de Imobilização Ortopédica',
  'Auxiliar de Laboratório',
  'Técnico de Laboratório',
  'Médico Cardiologista',
  'Médico Cirurgião Geral',
  'Médico Clínico Geral',
  'Médico Intensivista - UTI Adulto',
  'Médico Pediátra - UTI Pediátrica',
  'Condutor de Ambulância',
  'Técnico de Informática',
  'Analista de TI',
  'Analista de Segurança da Informação',
  'Diretor Geral',
  'Técnico de Enfermagem',
  'Médico',
  'Técnico de Radiologia',
  'Auxiliar de Limpeza',
  'Técnico de Laboratório',
  'Médico Ultrassonografia',
  'Médico Urologista',
  'Médico Nefrologista',
  'Médico Pediátra',
  'Médico Neurocirurgião',
  'Médico Cirurgião Plástico',
  'Médico Ginecologista e Obstetrícia',
  'Médico Gastroenterologista',
  'Médico Oftalmologista',
  'Engenheiro Civil',
  'Almoxarifado',
  'Analista de Rede',
  'Técnicos de Informática',
  'Auxiliar de Lavanderia',
  'Faturista',
  'Médico Auditor',
  'Analista Administrativo',
  'Técnico de Patologia Clínica',
  'Médico Anestesiologista',
  'Médico Ortopedista/Traumatologista',
  'Médico Radiologista',
  'Médico Psiquiatra',
  'Enfermeiro(a) Auditor',
  'Administrador Hospitalar',
  'Técnica de Higiene Dental',
  'Auxiliar de Patologia Clínica',
  'Médico Otorrinolaringologista',
  'Médico Cirurgião de Toráxico',
  'Médico Cirurgião Vascular',
  'Médico Neurologista',
  'Eletricista',
  'Responsável Técnico',
  'Camareira',
  'Coletador',
  'Agente de Administração',
  'Assessor(a) Técnico(a) II',
  'Coordenador de Unidade de Terapia Intensiva',
  'Médico Cirurgião Pediátrico',
  'Diretor de Unidade Hospitalar',
  'Assessor(a) Técnico(a) de Saúde IV',
  'Assessor(a) Técnico(a) I',
  'Estagiário(a) Nível Superior',
  'Médico Oncologista',
  'Médico Pneumologista',
  'Médico(a) Auditor(a)',
  'Residente Técnico/Bolsista',
  'Farmacêutico(a) Bioquímico(a)',
  'Técnico(a) de Farmácia',
  'Auxiliar de Cozinha',
  'Copeiro(a) Geral',
  'Gerente',
  'Clínico Geral',
  'Cirurgião Geral',
  'Cirurgião Dentista Bucomaxilofacial',
  'Apoio Administrativo',
  'Serviços Gerais',
  'Auxiliar de Farmácia',
  'Médico Neonatologista',
  'Arquivologista',
  'Advogado(a)',
  'Historiador(a)',
  'Analista de Sistemas - Administrador de Banco de Dados; Infraestrutura, O&M',
  'Estagiário(a) de Graduação',
  'Técnico em Manutenção de Equipamentos Médicos Hospitalares',
  outraEspecificar,
];
